[2021-07-14 20:34:13,049] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: MySQL.irpef_1 2021-07-14T20:32:22.335444+00:00 [queued]>
[2021-07-14 20:34:13,146] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: MySQL.irpef_1 2021-07-14T20:32:22.335444+00:00 [queued]>
[2021-07-14 20:34:13,150] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-14 20:34:13,158] {taskinstance.py:1088} INFO - Starting attempt 2 of 2
[2021-07-14 20:34:13,159] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-14 20:34:13,298] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): irpef_1> on 2021-07-14T20:32:22.335444+00:00
[2021-07-14 20:34:13,305] {standard_task_runner.py:52} INFO - Started process 5067 to run task
[2021-07-14 20:34:13,325] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'MySQL', 'irpef_1', '2021-07-14T20:32:22.335444+00:00', '--job-id', '58', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/third_dag.py', '--cfg-path', '/tmp/tmpbwm9zqba', '--error-file', '/tmp/tmp55hc73eq']
[2021-07-14 20:34:13,332] {standard_task_runner.py:77} INFO - Job 58: Subtask irpef_1
[2021-07-14 20:34:13,804] {logging_mixin.py:104} INFO - Running <TaskInstance: MySQL.irpef_1 2021-07-14T20:32:22.335444+00:00 [running]> on host bf600838264e
[2021-07-14 20:34:14,461] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=user
AIRFLOW_CTX_DAG_ID=MySQL
AIRFLOW_CTX_TASK_ID=irpef_1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-14T20:32:22.335444+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-14T20:32:22.335444+00:00
[2021-07-14 20:34:14,469] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2021-07-14 20:34:14,471] {base.py:78} INFO - Using connection to: id: mysql_test_conn. Host: 172.17.0.1, Port: 3310, Schema: project_bdt, Login: root, Password: ***, extra: {}
[2021-07-14 20:34:14,523] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/third_dag.py", line 71, in label_irpef
    cursor = conn.cursor()
TypeError: cursor() got an unexpected keyword argument 'buffered'
[2021-07-14 20:34:14,548] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=MySQL, task_id=irpef_1, execution_date=20210714T203222, start_date=20210714T203413, end_date=20210714T203414
[2021-07-14 20:34:14,683] {local_task_job.py:151} INFO - Task exited with return code 1
