[2021-07-14 18:19:01,782] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: bdt_2021_ETL.create_db_5 2021-07-14T18:16:59.219967+00:00 [queued]>
[2021-07-14 18:19:01,823] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: bdt_2021_ETL.create_db_5 2021-07-14T18:16:59.219967+00:00 [queued]>
[2021-07-14 18:19:01,824] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-14 18:19:01,826] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2021-07-14 18:19:01,828] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-14 18:19:01,913] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): create_db_5> on 2021-07-14T18:16:59.219967+00:00
[2021-07-14 18:19:01,925] {standard_task_runner.py:52} INFO - Started process 951 to run task
[2021-07-14 18:19:01,933] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'bdt_2021_ETL', 'create_db_5', '2021-07-14T18:16:59.219967+00:00', '--job-id', '33', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/second_dag.py', '--cfg-path', '/tmp/tmpaxldchuk', '--error-file', '/tmp/tmp5g35ul23']
[2021-07-14 18:19:01,935] {standard_task_runner.py:77} INFO - Job 33: Subtask create_db_5
[2021-07-14 18:19:02,442] {logging_mixin.py:104} INFO - Running <TaskInstance: bdt_2021_ETL.create_db_5 2021-07-14T18:16:59.219967+00:00 [running]> on host bf600838264e
[2021-07-14 18:19:02,768] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bdt_2021_ETL
AIRFLOW_CTX_TASK_ID=create_db_5
AIRFLOW_CTX_EXECUTION_DATE=2021-07-14T18:16:59.219967+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-14T18:16:59.219967+00:00
[2021-07-14 18:19:02,808] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2021-07-14 18:19:02,809] {base.py:78} INFO - Using connection to: id: mysql_test_conn. Host: 172.17.0.1, Port: 3310, Schema: project_bdt, Login: root, Password: ***, extra: {}
[2021-07-14 18:19:02,833] {dbapi.py:204} INFO - Running statement: CREATE TABLE `carcom14` ( `nquest` INT NOT NULL, 
`nord` INT NOT NULL, 
`sex` INT NOT NULL, 
`anasc` INT NOT NULL, 
`staciv` INT NOT NULL, 
`ireg` INT NOT NULL, 
`ncomp` INT NOT NULL, 
`perc` INT NOT NULL), parameters: None
[2021-07-14 18:19:02,906] {dbapi.py:212} INFO - Rows affected: 0
[2021-07-14 18:19:02,908] {python.py:151} INFO - Done. Returned value was: None
[2021-07-14 18:19:02,969] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=bdt_2021_ETL, task_id=create_db_5, execution_date=20210714T181659, start_date=20210714T181901, end_date=20210714T181902
[2021-07-14 18:19:03,109] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-14 18:19:03,151] {local_task_job.py:151} INFO - Task exited with return code 0
